networks:
  default:
    external: true
    name: kong-net

volumes:
  kong-db-data:

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong:
    image: kong:3.6
    container_name: kong
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    command: >
      sh -c "kong migrations bootstrap && kong start"
    ports:
      - "8000:8000"  # Proxy (consumidores)
      - "8001:8001"  # Admin API
    networks:
      - default

  konga:
    image: pantsel/konga:latest
    container_name: konga
    environment:
      - "KONGA_HOST=konga:1337"    # Dirección de Konga
      - "KONGA_PORT=1337"          # Puerto para acceder a la interfaz
      - "KONG_ADMIN_URL=http://kong:8001"  # Dirección del Admin API de Kong
    ports:
      - "1337:1337"  # Puerto para acceder a la interfaz de Konga
    networks:
      - default
    depends_on:
      - kong

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    networks:
      - default

  singer-service:
    build: ./singer-service
    container_name: singer-service
    ports:
      - "5001:5001"
    networks:
      - default

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5002:5002"
    networks:
      - default

  vote-service:
    build: ./vote-service
    container_name: vote-service
    ports:
      - "5003:5003"
    networks:
      - default

  
